server:
  port: 8000

eureka:
  client:
    fetch-registry: true # ??? ????? ???
    register-with-eureka: true # ??? ????? ???
    service-url:
      defaultZone: http://localhost:8761/eureka # ??? ?????? ??

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: llm-service
          uri: lb://LLM-SERVICE
          predicates:
            - Path=/python/**
          filters:
            # url ???
            # ?<???>? ?? ??? ???? ???? ??? ? ??? ??. ()? ??? ?? ?? -> segment? (.*)? ??
            # ??(,)? ???? ?? url? ??? url? ?????.
            # ?? ?? ??? ??? ${???}?? url ???? ?? / ?????? ?? ??.
            - RewritePath=/python/(?<segment>.*), /$\{segment}

#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:64412 # ???? ??, http://localhost:8000/user ? ???? http://localhost:64412 ? ???
#          predicates:
#            - Path=/user/** # ?? gateway ??? /user/**? ???? ?? user-service? ?????? ??
#
#        - id: order-service
#          uri: http://localhost:54412 # ??? ? ??, http://localhost:8000/order ? ???? http://localhost:54412 ? ???
#          predicates:
#            - Path=/order/** # ?? gateway ??? /order/**? ???? ?? order-service? ?????? ??