server:
  port: 64412

spring:
  config:
    import:
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-dev.yml
      - optional:configserver:http://config-service:8888
  profiles:
    active: local
    include: oauth
  application:
    name: user-service
  cloud:
    config:
      name: common
      profile: jwt, oauth

eureka:
  instance:
    instance-id: user-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/