server:
  port: 8761

spring:
  application:
    name: discovery-service #  Application ??? ??? ? ???, ??? ?? ???? application.name ?? ????.

eureka:
  client:
    register-with-eureka: false # ?? ??? ?????? ??????? ??? false ? ???? ??.
    fetch-registry: false # ?? ??? false? ???? ???, ??? ??? ??? ?????? ???? ??.
  server:
    enable-self-preservation: false