server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: git@github.com:westreed/MSA-Study-Config.git
          ignore-local-ssh-settings: true
          private-key: ${SSH_PRIVATE_KEY}
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256

encrypt:
  key: helloworld

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false

eureka:
  instance:
    instance-id: config-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/